### ISSUE TITLE
raw

### ISSUE THREAD

**Issue by bnomei** [AugustMiller/kirby-architect#8]
getting the labels is very useful indeed but in my case i needed a lot more from the blueprint to generate dynamic frontend forms matching the panel blueprint. especially the `required`setting and the `validate` with its property `match` to create regex for [parsley](http://parsleyjs.org).

```yml
fieldname:
  type: text
  validate:
    match: "/^\d{2}\.\d{4}$/"
anotherwithoutvalidate:
  type: email
```

getting that with the direct yml array is a bit hacky since the `match` propery was not needed in some blueprint field definitions.

```php
$mightbreak = Architect::field_info('variety', 'density')['validate']['match'];
$betterbutugly = a::get(Architect::field_info('variety', 'density'), 'validate', []), ''match', null);
```

i ended up with lots of if-clause testing and `a::get()` but maybe you can think of a better solution?
